#!/bin/bash

# Turn off the motherfucking bell.
 xset -b

# Set font directory
 xset +fp /usr/share/fonts/local
 xset +fp /home/igaray/.config/awesome/fonts
 xset fp rehash

# Enable restart X
 setxkbmap -option terminate:ctrl_alt_bksp &

# Swap left control and capslock keys to avoid emacs pinky.
 xmodmap -e "remove lock = Caps_Lock"
 xmodmap -e "add control = Caps_Lock"
 xmodmap -e "remove control = Control_L"
 xmodmap -e "add lock = Control_L"
 setxkbmap -option ctrl:swapcaps
 setxkbmap latam

#xrandr --output LVDS1 --mode 1280x800
#xrandr --output VGA1  --mode 1920x1080
#xrandr --output VGA1  --right-of LVDS1

#while true;
#do
#    for image in $(find /home/igaray/.config/awesome/wallpapers/ -iname '*.*' | sort -R); do
#        echo Setting background to: $image
#        hsetroot -full $image
#        sleep 5m
#    done
#done &
 hsetroot -full /home/igaray/Dropbox/system/wallpapers/wallpaper.jpg

 wmname LG3D

 urxvtd -q -o -f &
 mpd ~/.mpdconf &

#exec awesome
 exec dwm
#exec startlxde
#exec gnome-session
#exec gnome-session-cinnamon
#exec xmonad

