#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Turn off the motherfucking bell.
 xset -b

# Set font directory
 xset +fp /usr/share/fonts/local
 xset +fp /home/igaray/.config/awesome/fonts
 xset fp rehash

# Enable restart X
 setxkbmap -option terminate:ctrl_alt_bksp &

# Swap left control and capslock keys to avoid emacs pinky.
 xmodmap -e "remove lock = Caps_Lock"
 xmodmap -e "add control = Caps_Lock"
#xmodmap -e "remove control = Control_L"
#xmodmap -e "add lock = Control_L"
#setxkbmap -model us -variant intl -option ctrl:swapcaps
 setxkbmap -model us -variant intl -option ctrl:swapcaps

#xrandr --output LVDS1 --mode 1280x800
#xrandr --output VGA1  --mode 1920x1080

#feh --bg-fill /home/igaray/Dropbox/system/wallpapers/wallpaper.jpg
 feh --bg-max /home/igaray/.wallpaper.jpg

 wmname LG3D

 urxvtd -q -o -f &

 exec awesome
#exec dwm
#exec dbus-launch gnome-session
